/**
 * Export utility for CSV and print-to-PDF
 */

export function exportToCSV(data: Record<string, any>[], filename: string) {
  if (data.length === 0) return

  const headers = Object.keys(data[0])
  const csvContent = [
    headers.join(','),
    ...data.map(row => headers.map(h => {
      const val = row[h]
      const str = val === null || val === undefined ? '' : String(val)
      // Escape quotes and wrap in quotes if contains comma
      return str.includes(',') || str.includes('"') ? `"${str.replace(/"/g, '""')}"` : str
    }).join(','))
  ].join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = `${filename}_${new Date().toISOString().split('T')[0]}.csv`
  link.click()
  URL.revokeObjectURL(link.href)
}

export function exportTableToCSV(tableId: string, filename: string) {
  const table = document.getElementById(tableId)
  if (!table) return

  const rows = table.querySelectorAll('tr')
  const csvRows: string[] = []

  rows.forEach(row => {
    const cells = row.querySelectorAll('th, td')
    const rowData = Array.from(cells).map(cell => {
      const text = (cell as HTMLElement).innerText.trim()
      return text.includes(',') ? `"${text}"` : text
    })
    csvRows.push(rowData.join(','))
  })

  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv' })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = `${filename}_${new Date().toISOString().split('T')[0]}.csv`
  link.click()
}

export function printInvoice(bookingId: string, data: {
  customerName: string
  pickup: string
  drop: string
  truckType: string
  distance: string
  breakdown: { label: string; amount: number }[]
  total: number
  date: string
}) {
  const html = `
    <!DOCTYPE html>
    <html><head><title>Invoice - ${bookingId}</title>
    <style>
      body { font-family: 'Segoe UI', sans-serif; max-width: 700px; margin: 0 auto; padding: 40px; color: #212121; }
      .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #1B5E20; }
      .logo { font-size: 24px; font-weight: 900; color: #1B5E20; }
      .badge { background: #E8F5E9; color: #1B5E20; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 700; }
      table { width: 100%; border-collapse: collapse; margin: 20px 0; }
      th { text-align: left; padding: 10px; border-bottom: 2px solid #eee; font-size: 12px; color: #999; text-transform: uppercase; }
      td { padding: 10px; border-bottom: 1px solid #f5f5f5; }
      .total-row td { border-top: 2px solid #1B5E20; font-weight: 900; font-size: 18px; color: #1B5E20; }
      .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
      @media print { body { padding: 20px; } }
    </style>
    </head><body>
    <div class="header">
      <div class="logo">🚛 RaftaarFreight</div>
      <div>
        <div class="badge">INVOICE</div>
        <p style="font-size: 12px; color: #999; margin-top: 8px;">${data.date}</p>
      </div>
    </div>
    <p><strong>Booking ID:</strong> ${bookingId}</p>
    <p><strong>Customer:</strong> ${data.customerName}</p>
    <p><strong>Route:</strong> ${data.pickup} → ${data.drop}</p>
    <p><strong>Truck Type:</strong> ${data.truckType} • <strong>Distance:</strong> ${data.distance}</p>
    <table>
      <thead><tr><th>Item</th><th style="text-align:right">Amount (PKR)</th></tr></thead>
      <tbody>
        ${data.breakdown.map(b => `<tr><td>${b.label}</td><td style="text-align:right">₨${b.amount.toLocaleString()}</td></tr>`).join('')}
        <tr class="total-row"><td>TOTAL</td><td style="text-align:right">₨${data.total.toLocaleString()}</td></tr>
      </tbody>
    </table>
    <p style="font-size: 13px; color: #666;">GST included at 17%. This invoice is auto-generated by RaftaarFreight platform.</p>
    <div class="footer">
      <p>RaftaarFreight • www.raftaarfreight.pk • support@raftaarfreight.pk</p>
      <p>NTN: 1234567-8 • GST Reg: STRN-PK-2024-001</p>
    </div>
    </body></html>
  `

  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
    printWindow.print()
  }
}
